{"metadata": {"dbt_schema_version": "https://schemas.getdbt.com/dbt/run-results/v1.json", "dbt_version": "0.19.1", "generated_at": "2021-07-08T11:55:44.119667Z", "invocation_id": "f0c03c7f-e4b8-4adb-8689-97403dcfe480", "env": {}}, "results": [{"status": "success", "timing": [{"name": "compile", "started_at": "2021-07-08T11:55:41.014412Z", "completed_at": "2021-07-08T11:55:41.030412Z"}, {"name": "execute", "started_at": "2021-07-08T11:55:41.030575Z", "completed_at": "2021-07-08T11:55:42.104790Z"}], "thread_id": "Thread-1", "execution_time": 1.0910189151763916, "adapter_response": {"_message": "OK", "code": "CREATE VIEW"}, "message": "OK", "unique_id": "model.my_new_project.my_first_dbt_model"}, {"status": "error", "timing": [], "thread_id": "Thread-1", "execution_time": 2.010448932647705, "adapter_response": {}, "message": "Database Error in model my_second_dbt_model (models/example/my_second_dbt_model.sql)\n  Unrecognized name: id at [10:7]\n  compiled SQL at target/run/my_new_project/models/example/my_second_dbt_model.sql", "unique_id": "model.my_new_project.my_second_dbt_model"}], "elapsed_time": 3.490128755569458, "args": {"log_format": "default", "write_json": true, "profiles_dir": "/root/.dbt", "vars": "{}\n", "use_cache": true, "version_check": true, "full_refresh": true, "which": "run", "rpc_method": "run"}}